<?php echo AUTOGENERATED_CONFIGS; ?>

<?php /** @var Template_VariableAccessor $VAR */ ?>
<?php require_once('/usr/local/psa/admin/conf/templates/custom/lib/nat_resolve.inc.php');?>
<?php foreach ($VAR->server->ipAddresses->all as $ipAddress): ?>
server {
 <?php 
            $ip['public'] = $ipAddress->escapedAddress;
            $ip['private'] = nat_resolve($ipAddress->escapedAddress);

            if ( $ip['private']!= null ):
                foreach ($ip AS $ipaddress):
        ?>
    listen <?php echo $ipaddress.":{$VAR->server->nginx->httpPort}" ?>
    default_server <?php if ($ipAddress->isIpV6) echo 'ipv6only=on'; ?>;
    <?php endforeach; ?>
	<?php endif; ?>


    location / {
        proxy_pass http://<?php echo $ipAddress->proxyEscapedAddress . ':' . $VAR->server->webserver->httpPort ?>;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
<?php endforeach; ?>

<?php /* Next block used for watchdog */ ?>
<?php if (!$VAR->server->ipAddresses->hasIpV4Address): ?>
server {
    listen 127.0.0.1 default_server;
    return 200;
}
<?php endif ?>